stages:
    - build
#    - test
    
#before_script:
#    - apt-get update
#    - apt-get -y install
#        cmake
#        gobjc
#        gobjc++
#        libtiff-dev
#        liblcms2-dev
#        libgnustep-base-dev
#        libgsl-dev
#        libopenexr-dev

linux:
    stage: build
    script:
        - apt-get update
        - apt-get -y install
            cmake
            gobjc
            gobjc++
            libtiff-dev
            liblcms2-dev
            libgnustep-base-dev
            libgsl-dev
            libopenexr-dev
        - mkdir build
        - cd build
        - cmake ..
        - make
    artifacts:
    tags: 
        - linux

render:
    stage: build
    script:
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_INSTALL_PREFIX=~
        - make install
        - cd ..
        - git clone https://gitlab.com/art-development-team/art-functionality-test.git
        - git checkout v2.1
        - cd art-functionality-test
        - python art_functionality_test.py
        - mv output ..
    artifacts:
        when: always
        paths:
            - output
        reports:
            junit: output/report/junit.xml
    tags:
        - render
